In [ ]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
train_images[0].shape

(28, 28)

In [ ]:
print(train_images.shape)
#(60000, 28, 28)
print(len(train_labels))
#60000
train_labels
#array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

(60000, 28, 28)
60000


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
print(test_images.shape)
#(10000, 28, 28)
print(len(test_labels))
#10000
test_labels
#array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

(10000, 28, 28)
10000


array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [ ]:
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(1024, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(512, activation='relu'))
network.add(layers.Dense(2048, activation='relu'))
network.add(layers.Dense(10, activation='softmax'))

In [ ]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [ ]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [ ]:
train_images[0].shape

(784,)

In [ ]:
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [ ]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 16s 4ms/step - loss: 0.4806 - accuracy: 0.8508
Epoch 2/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0938 - accuracy: 0.9730
Epoch 3/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0665 - accuracy: 0.9816
Epoch 4/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0566 - accuracy: 0.9845
Epoch 5/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0530 - accuracy: 0.9868


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,500])

In [ ]:
a.shape

(5,)

In [ ]:
tup = ([1,2,3],[23,3,3])

In [ ]:
tup

([1, 2, 3], [23, 3, 3])